# Generated by Django 4.1.7 on 2023-02-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('num_bikes', models.IntegerField()),
                ('num_stations', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BikeStation',
        ),
    ]
