# Generated by Django 4.1.7 on 2023-02-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0003_bike_delete_bikeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('free_bikes', models.IntegerField()),
                ('empty_slots', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
    ]
