# Generated by Django 4.1.7 on 2023-02-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0005_alter_bikestation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikestation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
