# Generated by Django 4.1.7 on 2023-02-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('region', models.CharField(max_length=255)),
                ('tipo_proyecto', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
            ],
        ),
    ]
